language: php

php:
  - 5.6

services:
  - postgresql

env:
  global:
    - APP_ENV=local
    - APP_DEBUG=true
    - APP_KEY=base64:MOkFzFv5bw9l8VPq4AXr6n4+WsnrWpRJdmpMM5vN7/Y=
    - APP_URL=http://localhost
    - DB_CONNECTION=pgsql
    - DB_DATABASE=travis_ci_test
    - DB_USERNAME=postgres

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - composer self-update
  - cd ./tests
  - composer require satooshi/php-coveralls
  - composer update
  - php artisan migrate
  - php artisan db:seed
  - cd ..
  - mkdir -p build/logs

script: 
 - tests/vendor/bin/phpunit --coverage-clover build/logs/clover.xml tests/tests

after_script:
  - php tests/vendor/bin/coveralls -v
